# Generated by Django 3.2.19 on 2026-06-18 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(default='', validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
