# Generated by Django 6.0.6 on 2026-06-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='movie_format',
            field=models.CharField(default='2D', max_length=10),
        ),
    ]
