# Generated by Django 6.0.6 on 2026-06-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_booking_movie_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='movie_format',
        ),
    ]
