# Generated by Django 6.0.6 on 2026-06-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_seat_reserved_at_seat_reserved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='reserved_at',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='reserved_by',
        ),
    ]
