# Generated by Django 6.0.6 on 2026-07-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_booking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(db_index=True, default='PENDING', max_length=20),
        ),
    ]
