# Generated by Django 6.0.6 on 2026-07-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_booking_booked_at_booking_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(db_index=True, default='Action', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(db_index=True, default='Action', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genre', 'language'], name='movies_movi_genre_08a05d_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'),
        ),
    ]
